# Generated by Django 3.0.4 on 2020-03-23 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoastRoast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('bost_or_roast', models.CharField(choices=[('Boast', 'Boast'), ('Roast', 'Roast')], default='Boast', max_length=5)),
                ('body', models.TextField()),
                ('total_count', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
