# Generated by Django 3.0.4 on 2020-03-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boastroast',
            old_name='bost_or_roast',
            new_name='boast_or_roast',
        ),
    ]
