# Generated by Django 3.0.4 on 2020-03-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_backend', '0002_auto_20200323_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastroast',
            name='boast_or_roast',
            field=models.BooleanField(default=True),
        ),
    ]
